export const  RESET_INSTANCE_DATA = 'RESET_INSTANCE_DATA',
              RESET_META_DATA = 'RESET_META_DATA',
              FETCH_QUIZ_REQUEST = 'FETCH_QUIZ_REQUEST',
              FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS',
              FETCH_QUIZ_FAIL = 'FETCH_QUIZ_FAIL',

              START_TIMER = 'START_TIMER',
              END_TIMER = 'END_TIMER',

              SET_META_DATA = 'SET_META_DATA',
              SET_SELECTED_ANSWER = 'SET_SELECTED_ANSWER',
              SET_CLUE_FLAG = 'SET_CLUE_FLAG',              
              SET_NEXT_QUESTION = 'SET_NEXT_QUESTION',
              SET_QUIZ_COMPLETE_FLAG = 'SET_QUIZ_COMPLETE_FLAG',
              SET_USER_INITIALS = 'SET_USER_INITIALS',

              STACK_ANSWER = 'STACK_ANSWER',

              INCREMENT_CLUE_COUNT = 'INCREMENT_CLUE_COUNT',
              POST_PLAYTHRU_SUCCESS = 'POST_PLAYTHRU_SUCCESS';
              